name: signup-page
description: Building a Signup Page.

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter:
  uses-material-design: true
